### ISSUE TITLE
Link to TIA Portal project redirects wrong

### ISSUE THREAD

**Issue by HummelN7872** [industrial-edge/Performance-Analytics#7]
# Issue-template

## Summary

Link to the TIA Portal project [redirects wrong](https://github.com/industrial-edge/Performance-Analytics/blob/main/docs/Installation.md#configure-plc-project-in-tia-portal)

## Steps to reproduce

Click on the link [here](https://github.com/industrial-edge/Performance-Analytics/blob/main/src/StepTimeAnalysis.zap16)

Please add relevant screenshots and logs

![image](https://user-images.githubusercontent.com/74044913/216006629-1e6988ea-33e5-4773-b5ed-ced70ba609e8.png)

## Solution
Either fix the link or better upload a zap16 file instead of a ap16

**Comment by j0hannesfr** [comment]
project was to big for zap16 (>25MB), I fixed the link to the .7z file
