### ISSUE TITLE
Update Connectors

### ISSUE THREAD

**Issue by j0hannesfr** [industrial-edge/Performance-Analytics#8]
# Issue-template

## Summary

Description how to configure OPC UA in S7 Connector is outdated.  Add OPC UA Connector application or update completely to IIH.

## What is the current bug behavior?

You can't configure OPC UA connections with the S7 Connector anymore. The description should be updated, that you need both connector apps (S7 & OPC UA) now to perform the steps in this HowTo.

## Line of code

https://github.com/industrial-edge/Performance-Analytics/blob/main/docs/Installation.md#configure-s7-connector

**Comment by HummelN7872** [comment]
documentation was updated
